---

# docs: https://organize.readthedocs.io/en/latest/

rules:

  - name: Sposta le fatture elettroniche in emacs-org
    locations:
      - ~/Downloads
    filters:
      - name:
          startswith: IT
      - extension:
          - xml
    actions:
      - move: "~/repositories/emacs-org/2-area/finanze/fatture-elettroniche/"
      - shell: |
          cd ~/repositories/emacs-org/
          git add 2-area/finanze/fatture-elettroniche/{name}.{extension}

  - name: Converte le fatture elettroniche da p7m a xml e le mette in  emacs-org
    locations:
      - ~/Downloads
    filters:
      - name:
          startswith: IT
      - extension:
         - p7m
    actions:
      - shell: |
          openssl smime -decrypt -in {path} -inform DER -verify -noverify -out ~/repositories/emacs-org/2-area/finanze/fatture-elettroniche/{name}
          cd ~/repositories/emacs-org/
          git add 2-area/finanze/fatture-elettroniche/{name}
      - move: "~/repositories/emacs-org/2-area/finanze/fatture-elettroniche/"

  - name: Sposta i documenti da archiviare in Paperless nella dir CONSUME
    locations:
      - ~/Downloads
    filters:
      - name:
          contains:
            - invoice
            - fastweb
            - fattura
          case_sensitive: false
      - extension:
          - pdf
    actions:
      - move: "/Users/andrea/4ARCHIVE/PAPERLESS/CONSUME/"

  #- name: My first rule
  #  locations:
  #    - /tmp/
  #  actions:
  #    - echo: "Hello world"
  #  tags:
  #    - debug
  #    - fast

  #- name: Digital Conservation
  #  locations:
  #    - ~/Downloads
  #  filters:
  #    - name:
  #        contains:
  #          - "ewitness"
  #          - "digital-conservation"
  #          - "digital conservation"
  #          - "digital_conservation"
  #        case_sensitive: false
  #    - extension
  #  actions:
  #    - macos_tags:
  #        - "digital-conservation (orange)"
  #    - move: "~/storage/googledrive/1-projects/digital-conservation/{name.lower()}.{extension.lower()}"
      #- write:
      #    text: "{size.traditional} -- {relative_path}"
      #    path: "./storage-index.org"
      #    mode: "append"

  #- name: Multicerta
  #  locations:
  #    - ~/Downloads
  #  filters:
  #    - name:
  #        contains:
  #          - "multicerta"
  #        case_sensitive: false
  #    - extension
  #  actions:
  #    - macos_tags:
  #        - "multicerta (orange)"
  #    - move: "~/storage/googledrive/1-projects/multicerta/{name.lower()}.{extension.lower()}"

# todo: devo creare le corrispondenti regole anche con target "dir": https://organize.readthedocs.io/en/latest/rules/#targeting-directories
