---
repos:
  - repo: local
    hooks:
      - id: Validate organize config
        name: organize-check
        entry: ~/.organize/venv/bin/organize check
        language: system
        types: [file]
        files: ^(.*)organize-config(.*)\.(xml)$
        pass_filenames: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      # pre-commit install --hook-type commit-msg
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
